#!/bin/bash
echo
read -p "Are you sure " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[YyeEsS] ]]
	then


	# add changes
	git add -v .

	# commit

	if [ $# -eq 0 ]; then 
		# get commit message from prompt stdin
		echo -n "message: "
		read msg
		echo
	else 
		# get message from params
		msg=$(echo $@ | awk '// {print}')
	fi

	# commit
	git commit -m "$msg"

	# push
	git push

	echo
fi
