#!/bin/bash
echo

# add changes
git add -v .

# commit

if [ $# -eq 0 ]; then 
	# get commit message from prompt stdin
	echo -n "message: "
	read msg
	echo
else 
	# get message from params
	msg=$(echo $@ | awk '// {print}')
fi

# commit
git commit -m "$msg"

# push
git push

echo

