#!/bin/bash
echo

# add all changes
git add -v .

# commit

if [ $# -eq 0 ]; then 
	printf "message: "
	read msg
	echo
else 
	msg=$(echo $@ | awk '// {print}')
fi

git commit -m "$msg"

# push
git push

echo

